"""
Base strategy class for Polymarket trading strategies.

All strategies should inherit from BaseStrategy and implement:
- analyze_market(market): Returns trading signal or None
- on_position_opened(position): Called when position is opened
- on_position_closed(position): Called when position is closed
"""

from abc import ABC, abstractmethod
from typing import Dict, Optional, List
from dataclasses import dataclass
from datetime import datetime


@dataclass
class TradingSignal:
    """Trading signal generated by a strategy."""
    
    action: str  # 'buy' or 'sell'
    market_id: str
    outcome: str  # 'Yes' or 'No'
    size: float  # Position size in $
    confidence: float  # 0.0 to 1.0
    reason: str  # Human-readable explanation
    metadata: Dict = None  # Additional strategy-specific data


@dataclass
class Market:
    """Polymarket market data."""
    
    id: str
    question: str
    category: str
    end_date: datetime
    yes_price: float  # Current Yes price (0.0 to 1.0)
    no_price: float  # Current No price (0.0 to 1.0)
    volume_24h: float
    liquidity: float
    created_at: datetime
    metadata: Dict = None


@dataclass
class Position:
    """Open position."""
    
    market_id: str
    outcome: str
    size: float  # Position size in $
    entry_price: float
    current_price: float
    unrealized_pnl: float
    opened_at: datetime


class BaseStrategy(ABC):
    """
    Base class for all Polymarket strategies.
    
    Subclasses must implement:
    - analyze_market(market): Core strategy logic
    
    Optional overrides:
    - on_position_opened(position): React to new positions
    - on_position_closed(position): React to closed positions
    - filter_markets(markets): Pre-filter markets before analysis
    """
    
    def __init__(self, config: Dict):
        """
        Initialize strategy with configuration.
        
        Args:
            config: Strategy configuration dict
                Common keys:
                - min_edge: Minimum edge to trade (default: 0.05)
                - max_position: Max $ per position (default: 100)
                - max_portfolio_pct: Max % of portfolio per position
        """
        self.config = config
        self.positions: List[Position] = []
        self.closed_trades: List[Position] = []
        
    @abstractmethod
    def analyze_market(self, market: Market) -> Optional[TradingSignal]:
        """
        Analyze a market and generate a trading signal.
        
        Args:
            market: Market data
            
        Returns:
            TradingSignal if trade opportunity found, None otherwise
        """
        pass
    
    def filter_markets(self, markets: List[Market]) -> List[Market]:
        """
        Pre-filter markets before analysis.
        
        Override to implement custom filtering (e.g., by category,
        liquidity, time to expiry).
        
        Args:
            markets: All available markets
            
        Returns:
            Filtered list of markets to analyze
        """
        return markets
    
    def on_position_opened(self, position: Position):
        """
        Called when a position is opened.
        
        Override to implement custom logic (e.g., set stop losses,
        alerts, etc.).
        """
        self.positions.append(position)
        
    def on_position_closed(self, position: Position):
        """
        Called when a position is closed.
        
        Override to implement custom logic (e.g., performance tracking,
        strategy adjustment).
        """
        if position in self.positions:
            self.positions.remove(position)
        self.closed_trades.append(position)
        
    def calculate_position_size(self, edge: float, confidence: float = 1.0) -> float:
        """
        Calculate position size using Kelly criterion (fractional).
        
        Args:
            edge: Estimated edge (true_prob - market_price)
            confidence: Confidence in estimate (0.0 to 1.0)
            
        Returns:
            Position size in $
        """
        # Fractional Kelly (1/4 Kelly for safety)
        kelly_fraction = 0.25
        
        # Kelly formula: f = edge / odds
        # For binary outcome: f = (p * b - (1-p)) / b
        # Simplified: f = edge (when b ≈ 1)
        kelly_size = edge * kelly_fraction * confidence
        
        # Apply position limits
        max_position = self.config.get('max_position', 100)
        return min(kelly_size * max_position, max_position)
    
    def get_metrics(self) -> Dict:
        """
        Calculate strategy performance metrics.
        
        Returns:
            Dict with performance metrics
        """
        if not self.closed_trades:
            return {
                'total_trades': 0,
                'win_rate': 0.0,
                'avg_pnl': 0.0,
                'total_pnl': 0.0,
            }
        
        wins = [t for t in self.closed_trades if t.unrealized_pnl > 0]
        total_pnl = sum(t.unrealized_pnl for t in self.closed_trades)
        
        return {
            'total_trades': len(self.closed_trades),
            'win_rate': len(wins) / len(self.closed_trades),
            'avg_pnl': total_pnl / len(self.closed_trades),
            'total_pnl': total_pnl,
            'open_positions': len(self.positions),
        }
